mirumee/ariadne

ariadne/make_executable_schema.py, tests/test_mutations.py, tests/test_queries.py
Automatically define the schema based on existing types if one is not already provided.
Allows us to use examples closer to these used by Apollo.
Unfortunately I don't have the time necessary to provide a better test suite.
=> Automatically define schema based on types

tests/test_mutations.py, tests/test_queries.py
This PR adds tests for query and mutation that use `input` types for data.
Fixes #17
=> Test input types in query and mutation

README.md
Update quickstart in readme to dont show `schema {}`, because we don't need it anymore.
=> Remove schema from readme example

.pylintrc, .travis.yml, ariadne/resolvers.py, tests/snapshots/snap_test_introspection.py, tests/test_introspection.py
This PR changes the `add_resolve_functions_to_object` so it no longer breaks types that already had resolvers defined on them, namely `__Schema` type and friends.
=> Schema introspection

setup.py
Bump version to 0.0.3 and release GraphQL middleware to hyper-early adopters.
=> Release version 0.0.3 on pypi

tests/test_enums.py
We need to be compatible with [Enum definitions](https://graphql.org/learn/schema/#enumeration-types).
This PR explores this functionality from testing side and ensures our compatibility for future.
fixes #27
=> Introduce enums

requirements-dev.in, requirements-dev.txt
This PR adds the `pytest-mock` package required in the tests.
=> Add pytest-mock to dev dependencies

docs/mutations.rst
This PR defines custom object types for exemplary mutations. It's a good practice to define an object type for each migration separately, even if they initially contain the same fields.
=> Define object types for mutations

.travis.yml, CHANGELOG.md, CONTRIBUTING.md, ariadne/executable_schema.py, docs/index.rst, setup.py
This PR also adds `CHANGELOG.md` file for tracking changes in new versions.
Fixes #31
=> Bump python requirement to 3.6, add 3.7 to tests matrix and drop 3.5

CHANGELOG.md, README.md, ariadne/__init__.py, ariadne/utils.py, docs/introduction.rst, tests/test_gql_util.py
This PR adds `gql()` utility function for declaration-time validation of GraphQL strings and coloring/in IDE validation using Apollo-GraphQL in Python code.
Fixes #47
=> Add gql() utility

CHANGELOG.md, README.md, ariadne/__init__.py, ariadne/utils.py, docs/introduction.rst, docs/wsgi-middleware.rst, tests/test_start_simple_server.py
This PR adds `start_simple_server()` utility function, allowing us to shave off some complexity from minimal API examples and introductions.
Fixes #48
=> Add simple server util

CHANGELOG.md, tests/test_start_simple_server.py
I wasn't entirely happy with all changes introduced in  #68, so I am following up with new PR:
- Reworded changelog a little.
- Move some `start_simple_server` tests to fixtures that better represent real-world use.
=> Re-word changelog and make test fixtures little more real-worldly

readthedocs.yml
This PR adds `readthedocs.yml` file that tells RTD to use py3.6 for docs builds.
=> Add readthedocs.yml config to force py3.6 for docs builds

ariadne/types.py
Our current type annotation for `Resolver` doesn't support resolvers accepting arguments, thus introducing noise to `Mypy` that resolver function doesn't meet the signature of `[Any, GraphQLResolveInfo]`.
This problem is [known to MyPy authors](https://github.com/python/typing/issues/264), but in the meantime we should update our `Resolver` type to be more forgiving so dev tools and code linters don't confuse devs using Ariadne.
This PR changes annotation to `Callable[..., Any]`.
=> Fix type definition for Resolver

README.md
This PR fixes readme after changes to read the docs configuration I've did few days back:
- all links to docs in readme always point to latest released version's docs
- badge under logo displays build status for master, but also links to latest release version (I'll rather confuse devs working on Ariadne than confuse devs looking for stable docs)
=> Fix docs badge and link in readme

README.md
This PR changes logo link in readme to use updated version published on master of our docs.
=> Link to logo in master docs version

setup.py
This PR bumps version number for Ariadne to 0.2.0b1, so we can make beta release on PYPI before proper 0.2.0 release after new year.
=> Bump python package version number to 0.2.0b1

CHANGELOG.md, setup.py
This PR bumps version to 0.2.0 and adds release date for 0.2.0 entry in our changelog.
Note: merging this PR doesn't equal pypi push, we still have a moment to do last-second changes if we  need.
=> Bump version to 0.2.0 and add release date to changelog

CHANGELOG.md, ariadne/__init__.py, ariadne/enums.py, docs/enums.rst, tests/test_enums.py
This PR adds `Enum` *bindable* that takes name of enum in schema and dict of mappings, enabling easy transformation of enum values between GraphQL and internal representation:
```
role = Enum(
"role",
{
"ADMIN": 1,
"MODERATOR": 2,
"MVP": 4,
"REGULAR" 5,
"PROBATION": 6,
}
)
```
Fixes #39
=> Support transforming enum values to internal representation

CHANGELOG.md, README.md, ariadne/resolvers.py, ariadne/types.py, docs/index.rst, docs/mutations.rst, docs/resolvers.rst, docs/subscriptions.rst, tests/test_resolver_map.py
As simple as that. Subscriptions.
Bear in mind that as long as the example server is synchronous, the subscriptions won't work with the example server.
I'm not a fan of the API we're ending up with for the `ResolverMap`.
I think I'd prefer:
```python
sub_map = ResolverMap("Subscription")
@sub_map.add_field("counter")
def counter(count, info):
return count
@sub_map.add_source("counter")
async def tick(root, info):
...
```
They also look better when used as non-decorators:
```python
sub_map.add_field("counter", resolver=counter)
sub_map.add_source("counter", generator=tick)
```
=> Add subscriptions

docs/modularization.rst
Just a quick typo fix I spotted while reading docs.
(Also, I'm really excited to have discovered `ariadne`, it looks great!)
=> [docs/modularization] Fix missing close quotation mark

CHANGELOG.md, README.md, ariadne/__init__.py, ariadne/unions.py, docs/index.rst, docs/unions.rst, tests/test_unions.py
This PR adds support for `union` types in GraphQL.
This is achieved by introduction of `ariadne.Union` bindable that takes name of union, and resolver function that takes any object and is expected to return `None` or `str` with GraphQL type name.
`Union` also implements new API as discussed in #98:
```
union = Union("Name", type_resolver)
@union.type_resolver
def resolver(*_):
...
```
=> Add unions

tests/wsgi/test_request_dispatching.py
This PR redoes assertions in `wsgi.test_request_dispatching` to use `assert_called_once_with` instead for our custom args deconstruction code. It also introduces `InstanceOfHttpMethodNotAllowedError` testing util that lets us test with `assert_called_*_with` if one of arguments was instance of `HttpMethodNotAllowedError`.
=> Fix pylint errors introduced by recent PyLint

CHANGELOG.md, README.md, ariadne/__init__.py, ariadne/interfaces.py, ariadne/resolvers.py, docs/index.rst, docs/interfaces.rst, docs/unions.rst, tests/test_interface.py, tests/test_interfaces.py, tests/test_unions.py
This PR adds `Interface` type to Ariadne. Interface acts like the union, except it enforces intersection between implementing types. It also allows (optional) resolvers reuse between implementing types.
~~Currently, this is a proof-of-concept implementation.~~
=> Add interfaces

ariadne/scalars.py, ariadne/wsgi.py, pyproject.toml
This PR adds `pyproject.toml` file that excludes bunch of directories from black, including `snapshots` dir created by pytest snapshot plugin.
=> Setup black to ignore tests snapshots

ariadne/format_errors.py, tests/test_error_formatting.py
This PR replaces default `repr` with `reprlib.repr` util that handles exceptions coming from the `__repr__` and is also a function used by Python debugger.
=> Handle exceptions occuring during context repr() creation

docs/custom-server.rst
The Django example imported `graphql_sync` from ariadne but also from graphql. The import from graphql should be removed and is a artifact of the old example when ariadne offered no graphql_sync function (before version 0.3.0).
=> Removed duplicate import in Django example

docs/conf.py, docs/custom-server.rst, requirements-dev.in, requirements-dev.txt
I've removed the now-duplicate description of `make_executable_schema` and instead have included the convenience functions needed for clean integration.
=> Improve integration docs

CHANGELOG.md, docs/custom-server.rst, docs/index.rst, docs/integrations.rst
This PR renames "custom servers" doc to "integrations", adds Flask example and expands upon general integration process by providing simple step-by-step implementation instruction in addition to our boilerplate for integrators.
=> Change custom servers doc to "integrations"

CHANGELOG.md, ariadne/objects.py, ariadne/subscriptions.py, tests/test_objects.py, tests/test_subscriptions.py
This PR adds checks to `field` and `source` decorators that raise `ValueError` when name argument is not `str`:
```
@foo.field
def resolve_smth(*_):
...
```
Fixes #151
=> Add name checks for field and source decorators

CHANGELOG.md, ariadne/executable_schema.py, tests/test_modularization.py
This PR changes `make_executable_schema` implementation so its possible to use `extend type` in passed SDL, opening new ways for applications modularization.
Fixes #135 #95
=> Extend schema types

ariadne/asgi.py
This PR removes unused `extract_data_from_websocket` method from `asgi.GraphQL` that was superseded by `graphql.subscription` utility.
=> Remove unused extract_data_from_websocket

CHANGELOG.md, ariadne/enums.py, ariadne/executable_schema.py, tests/test_enums.py
This PR updates `make_executable_schema` to set default enum values for unset values.
Fixes #171
=> Set default enums values in schema

ariadne/asgi.py, ariadne/graphql.py, ariadne/logger.py, ariadne/wsgi.py, docs/logging.rst, tests/asgi/test_configuration.py, tests/wsgi/test_configuration.py
This PR simplifies loggers configuration so `logger` option is used for logger name, not `logging.Logger` instance.
=> Simplify logger configuration

docs/integrations.rst
I've missed the part about adding `ariadne.contrib.django` to `INSTALLED_APPS`, wich is kind of important because we rely on APPS template loader for playground.
=> Fix django integration example to mention django app

CHANGELOG.md, requirements-dev.in, requirements-dev.txt, requirements.txt, setup.py
This PR removes Starlette from `requirements-dev` because its already in main reqs, removes sphinx from deps and bumps GraphQL Core Next to 1.0.4.
=> Clean deps

MANIFEST.in, setup.py
Closes #180.
```
(saleor-venv) mbp-mikailkocak:ariadne mikailkocak$ rm -R *.egg* && ./setup.py sdist | grep -E 'typed|html'
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
copying ariadne/py.typed -> ariadne-0.4.0/ariadne
copying ariadne/contrib/django/templates/ariadne/graphql_playground.html -> ariadne-0.4.0/ariadne/contrib/django/templates/ariadne
```
=> Make setup.py executable and include templates in dist

.pylintrc, ariadne/asgi.py, ariadne/graphql.py, tests/asgi/test_query_execution.py, tests/wsgi/conftest.py, tests/wsgi/test_query_execution.py
This PR disables some checks that pylint did but either didn't bother us, or when they did, it would be a massive pain to workaround making it not worth in the first place:
- `broad-except`
- `too-complex`
- `too-many-arguments`
- `too-many-branches`
- `too-many-locals`
- `too-many-nested-blocks`
- `too-many-statements`
=> Make pyLint more lenient

ariadne/exceptions.py, ariadne/objects.py
This is just minor consistency polish. 😃 
There are a couple constructors defined without a return type.  mypy complains when initializing these objects in a typed codebase.
=> Add missing constructor return type annotations

ariadne/types.py
This PR adds `# pragma: no cover` comments to `parsing_started` and `parsing_finished` hooks in `Extension` type.
=> Add pragma no cover to all extension's hooks

ariadne/graphql.py
This PR updates our extensions system to call `has_errors` if query executed, but had some errors (eg. errors in resolvers). This potentially should enable better error logging in future extensions.
=> Call has_errors hook if successfully query had result.errors

CHANGELOG.md, README.md, ariadne/scalars.py, requirements.txt, tests/snapshots/snap_test_introspection.py, tests/test_custom_scalars.py
This PR updates `graphql-core-next` to 1.1.1, fixing our tests failures.
=> Update graphql-core-next to 1.1.1

CHANGELOG.md, ariadne/asgi.py, tests/asgi/test_configuration.py
This PR awaits custom callable `context_value`, if its coroutine.
Fixes #227
=> Await callable context value in ASGI

.gitignore
This is extra file that PIP generates on `pip install`, and shouldn't be commited.
=> Gitignore pip-wheel-metadata

CHANGELOG.md, ariadne/__init__.py, ariadne/format_error.py, tests/test_error_formatting.py
This PR moves all of `format_error` API to public space, so devs writing custom implementations don't have to dig those out from private API, or invent custom ones.
=> Make error formatting utils public

ariadne/contrib/tracing/apollotracing.py, ariadne/contrib/tracing/opentracing.py, ariadne/graphql.py, ariadne/types.py, ariadne/wsgi.py, requirements-dev.in, requirements-dev.txt, tests/test_extensions_sync.py, tests/tracing/test_apollotracing_sync.py, tests/tracing/test_opentracing_sync.py, tests/wsgi/conftest.py, tests/wsgi/test_configuration.py, tests/wsgi/test_query_execution.py
(This is a work in progress.)
These changes seemed to work with the following test:
```
from ariadne.types import ExtensionSync
...
class TimestampExtension(ExtensionSync):
def format(self):
return {"timestamp": datetime.now().isoformat()}
...
graphql_sync(
schema,
...
extensions=[TimestampExtension]
```
This also worked if I left off extensions as a kwarg in graphql_sync's call to execute so there may be other test cases that should be checked with this. Is this sufficient to support extensions for synchronous calls or is there another issue that needs to be handled in order for this to work correctly?
=> Support extensions for graphql_sync

ariadne/contrib/tracing/opentracing.py, ariadne/extensions.py, ariadne/types.py, tests/test_extensions.py, tests/test_extensions_sync.py, tests/tracing/snapshots/snap_test_apollotracing_sync.py
This PR is accumulation of few small extensions cleanups:
- Commited snapshot for sync apollo tracing extension test (cleanup after #239).
- Removed `error` from `request_finished` hook (fixes #242).
- Added tests checking if noop extensions hooks implemented in base classes don't interrupt query execution  (discussed in #239).
=> Misc extensions cleanups

ariadne/schema_visitor.py, tests/test_directives.py
This might be handy and make it easier to implement some directives like `@key` that needs to create a `_Entity` union type etc.
=> Iterate over copy of the map in case directives need to add types

ariadne/contrib/tracing/apollotracing.py, ariadne/extensions.py, ariadne/graphql.py, ariadne/types.py, tests/test_extensions.py, tests/test_extensions_sync.py
This PR is an exploration for how we could improve how extension hooks are passed the context. I've changed `ExtensionManager` implementation so context is passed to it together with extensions list. This gives manager single point for obtaining context for the current request, simplifying its calls in `graphql()`, and letting us pass `context` to extensions `has_errors` hook in a clean way.
Considered that extensions themselves are instantiated for the duration of request, we could also remove it from hooks, and instead update extension API so they are initialized with context as only argument, eg:
```
class MyExtension(Extension):
def __init__(self, context: ContextValue):
self.context = context
def has_errors(self, errors: List[GraphQLError]): …
```
=> Pass request context to manager instance, and from there to hooks

ariadne/executable_schema.py, tests/test_executable_schema_validation.py
Code and tests to add schema validation to `make_executable_schema`. Fixes issue #251
=> Add schema validation to make_executable_schema

CHANGELOG.md, ariadne/load_schema.py, tests/test_schema_file_load.py
Now, when providing path to load multiple schema files, we traverse the tree in search of _.graphql_ files.
=> Recursively load schema from path

ariadne/asgi.py, ariadne/graphql.py, tests/asgi/test_websockets.py
When creating a WS connection with Apollo as a JS client, it's possible to also send queries on the same channel, not only subscription requests. This PR implements that on the server-side.
=> Allow queries on the same channel.

setup.py
When installing using 'pip install -e .' in a venv for python 3.8.2 on a windows 10 machine, saw an error which the last few lines read: 
File "setup.py", line 19, in <module>
README = f.read()
File "C:\python3\lib\encodings\cp1252.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4913: character maps to <undefined>
Fix suggested by https://stackoverflow.com/questions/49640513/unicodedecodeerror-charmap-codec-cant-decode-byte-0x9d-in-position-x-charac
Installation succeeded with this fix.
=> fix setup.py for UnicodeDecodeError in cp1252.py

ariadne/utils.py, tests/test_kwargs_camel_case_conversion.py
The default decorator doesn't support converting values found inside lists to snake case. This leads to some weird inconsistencies when dealing with lists of custom object types. This change ensures that the snake-casing is applied to all levels of the object tree.
Example
--------
```
input Organization {
orgName
}
input Project {
parentOrgs: [Organization]
}
@mutation.field('createProject')
@convert_kwargs_to_snake_case
def create_project(_, info, project):
print(project['parent_orgs'][0]['org_name'])
```
=> Adds snake_caseing to complex values inside lists

CHANGELOG.md, ariadne/asgi.py, tests/asgi/test_websockets.py
This PR fixes #323 by rolling back changes from #288.
Also fixes #320
=> Roll-back #288: remove query/mutation execution over the websocket

CHANGELOG.md, requirements.txt, setup.py
This is stop-gap fix for #345 
For 0.11 we should just freeze graphql-core to 3.0.3
=> Freeze graphql-core dep at 3.0.3

CHANGELOG.md, ariadne/wsgi.py
In our docs we keep using `info.context` as dict with `request` key , but in WSGI app we default to `environ`. This change replaced default context for WSGI app with `{"request": environ}` so it's shape follows what we are describing in docs.
=> Change default context in WSGI app to be dict with request key

CHANGELOG.md, ariadne/scalars.py, tests/test_custom_scalars.py
The `default_literal_parser()` function in `ariadne.scalars` returns `ast.value`. However, in the case that `ast` is a node such as `ObjectValueNode` or `ListValueNode`, this causes an exception because these nodes do not have a value member.
Fixed by parsing `ast` with `graphql.utilities.value_from_ast_untyped`.
Fixes #356
=> Use graphql.utilities.value_from_ast_untyped to parse ast in default literal parser

ariadne/contrib/tracing/apollotracing.py, ariadne/contrib/tracing/opentracing.py, ariadne/schema_visitor.py, ariadne/types.py, requirements-dev.txt
Pylint 2.5 detects when overridden async method is declared as sync (and viceversa), causing PR #385 bumping pylint to fail.
This PR fixes all four linting errors occurring on pylint 2.5.3
=> Fix linting errors occuring on pylint 2.5

ariadne/scalars.py, tests/django/test_scalars.py, tests/test_custom_scalars.py
I've did deep dive into GraphQL's query executor and found that if scalar has no literal parser, GraphQL executor will use default one, which did exactly what our default one, eg. convert AST value to python type, then call `parse_value` for field.
In this PR I've added tests cementing this behavior in the core, and removed our fallback default literal parser. I'll also open issue on our docs to remember to update that `parse_literal` is not required if your scalar doesn't need custom AST unpacking logic.
Fixes #371
=> Don't create custom literal parser by default

ariadne/utils.py, tests/test_case_convertion_util.py
Updated convert_camel_case_to_snake to not add an additional underscore, if the previous char was already one.
This is useful for example for django users, when using it's nested lookups.
The previous version of the convert_camel_case_to_snake would add an additional underscore to the string, the new one prevents this behaviour.
So passing a string like "user__accountId" now results in "user__account_id" (2 underscores) instead of "user___account_id" (3 underscores).
=> Updated convert_camel_case_to_snake to handle more edge cases.

ariadne/utils.py, tests/test_case_convertion_util.py
Do not add an underscore, if the previous character was also upper case.
This is useful if you have an acronym in an identifier. Specifically, I encountered this with the identifier `interfaceMACs`, which converted to `interface_m_a_cs`. With this change the identifier converts to `interface_macs`.
=> Do not add underscores in block capitals in identifiers

ariadne/contrib/federation/utils.py, tests/federation/test_schema.py
Hello! My original federation PR contained an oversight on my part that wrongly added `__typename` to `None` when resolving entities. As can be seen in the [federation specs](https://www.apollographql.com/docs/federation/federation-spec/) and the original [federation-js source](https://github.com/apollographql/federation/blob/49fc528be1c2796b09fe7dff4f8cbe604b39a3fb/federation-js/src/types.ts#L44), the typename should not be added, as entities can return a non-nullable list of nullable `_Entity` types.
This PR addresses this oversight and tweaks one of the test files. Cheers!
=> Ensure None entities are returned as such during federation (without appending typename)

ariadne/validation/query_cost.py, tests/test_query_cost_validation.py
This PR makes a query cost validator to accept deep nested variables like `input` type values.
For example, when a multiplier name is `foo.bar.baz` ,  the multiplier value is `{"foo" : {"bar" : {"baz" : <value>}}}` .
See https://github.com/pa-bru/graphql-cost-analysis#cost-settings-arguments
note: CRLF was used in the 2 changed files, but most of `ariadne` used LF, so I fixed that newlines.
=> Fix cost multiplier to accept nested variables

ariadne/asgi.py, ariadne/contrib/django/views.py, ariadne/extensions.py, ariadne/graphql.py, ariadne/types.py, ariadne/wsgi.py
This consolidates the definition of the ExtensionList type into ariadne.types, where it can be referenced by everything that needs it.
The type definition has been updated to support a list of both Extension classes and callables that return Extension objects. This should be allowed since all that's happening with the items in this list is calling them: https://github.com/mirumee/ariadne/blob/master/ariadne/extensions.py#L21
=> Fixed type annotation for extensions list

ariadne/utils.py, tests/test_case_convertion_util.py
The previous version of the 'convert_camel_case_to_snake' utility function did not handle numbers inside the 'graphql_name'.
So passing a string like "foo365Bar" woud have resulted in "foo365_bar".
Now it would result in: "foo_365_bar"
=> Added support for numbers in camelCase variables.

CHANGELOG.md, ariadne/asgi.py, ariadne/contrib/federation/utils.py, ariadne/schema_visitor.py, requirements.txt
This PR updates GraphQL core to latest version: 3.1.3
=> Update GraphQL core to latest version

ariadne/utils.py, tests/test_camel_case_to_snake_case_convertion.py
Fixes #442, adds two new replace rules:
- `test134` -> `test_134`
- `HTTPRequest` -> `http_request`
=> Fix #442, append underscore when word is followed by digits

.github/ISSUE_TEMPLATE/config.yml, README.md, readthedocs.yml
GitHub bought Spectrum some time ago and is currently [sunsetting it](https://spectrum.chat/spectrum/general/join-us-on-our-new-journey~e4ca0386-f15c-4ba8-8184-21cf5fa39cf5) in favor of GH discussions.
I'm not biggest fan of how those are looking like now, but I'm finding them much less quirky to use than Spectrum, and, on flip side, we can easily convert issues to those without extra burden on original poster.
This PR also nukes extra erad the docs config file as we don't use those anymore.
Fixes #478
I'll open next PR on `ariadne-website` repo.
=> Fix #478: Update links to point to GitHub discussions

CHANGELOG.md, ariadne/asgi.py, tests/asgi/test_websockets.py
Adds `on_connect` and `on_disconnect` options to ASGI GraphQL app and introduces connection context.
`on_connect` is optional callable that is called when GraphQL client opens WebSocket connection with the server. It's called with two arguments: `WebSocket` instance and `Any` value with connection payload. It can be used to extract supported data from connection's payload to the current scope:
```python
def on_connect(ws: WebSocket, payload: Any):
if not isinstance(payload, dict):
return
ws.scope["auth"] = get_user_from_token(payload.get("auth_token"))
def get_context_value(request):
if request.scope.type == "websocket":
return {"auth": request.scope["auth"]}
return {"auth": get_user_from_token(request.headers.get("authorization")}
```
As bonus, users may raise new …
=> Add on_connect/on_disconnect hooks to ASGI app, support connection context

ariadne/executable_schema.py
It turns out that  `validate_schema` called in https://github.com/mirumee/ariadne/blob/master/ariadne/executable_schema.py#L26 is not needed here. 
In the other hand, `assert_validate_schema` is called here: https://github.com/mirumee/ariadne/blob/master/ariadne/executable_schema.py#L40 which is sufficient. 
Fixes #523
=> Remove superfluous schema validation

ariadne/asgi.py
Fixes pylint warning complaining that we are iterating on subscription keys to modify dict's values, eg:
```python
for key in some_dict:
some_dict[key].do_smth()
```
Where we could do:
```python
for value in some_dict.values():
value.do_smth()
```
=> Fix pylint warning

CHANGELOG.md, ariadne/validation/query_cost.py, tests/test_query_cost_validation.py
Fixes `multipliers` option handling in query cost calculation, so when value specified in multipliers is not set (because its optional), it's treated as `0` instead of validator raising error on `None` not being addable to `0`.
Fixes #716
=> Fix query cost calculation multiplier handling

ariadne/asgi.py
Extract's JSON response creation into `create_json_response` function that can be overridden to use custom JSON response, sec custom headers/cookies based on `response.state`, etc. ect.
Supersedes #650
=> Make json response more customizable

.github/workflows/tests.yml, CHANGELOG.md, setup.py
Removes unsupported Python version from test grid and packages manifest.
=> Remove Python 3.6 support

ariadne/contrib/tracing/apollotracing.py, ariadne/contrib/tracing/utils.py, ariadne/resolvers.py, tests/tracing/test_utils.py
Adding the option to trace default resolvers if someone want. This is actually very useful in tracing base field types for which resolvers are not explicitly set because those can be use in apollo studio to see which fields are being accessed and how much thereby helping api lifecycle management
=> Added option to trace default resolvers as well

ariadne/contrib/federation/utils.py
#775 Introduced a performance issue: https://github.com/mirumee/ariadne/issues/775#issuecomment-1102335619
The solution is to add start and end anchors to the comment regexes.
=> Directive definition regex pref

.github/workflows/tests.yml, ariadne/contrib/federation/utils.py
The main performance problem comes from `(?:\"{3}(?:[^\"]|[\s])*?\"{3})`.
The lazy '*?' drastically kills the performance of any federated graph that uses block comments, even if that graph is valid and has no custom directives.
Additionally, the old solution creates a run away regex with something like this: (4 quotes)
```
""""
Any Description
"""
directive @custom on FIELD
type Query {
rootField: String @custom
}
```
New solution will just ignore this comment.
```
""""
Any Description
"""
type Query {
rootField: String @custom
}
```
=> Federated graph regex performance. 

ariadne/contrib/federation/schema.py, ariadne/contrib/federation/utils.py, tests/federation/test_schema.py
As noted in #846, Ariadne currently doesn't support Federation 2, although it is currently possible to shim support by adding in the directive definitions manually. 
Instead of that, this PR allows Federation 2 schemas to be parsed without those additional definitions. Additionally, it supports detection of Federation 2 schemas via use of a regex (https://github.com/mirumee/ariadne/blob/cc2a4afbd53101b8bf98e382a4090da348252fab/ariadne/contrib/federation/schema.py#L89) to ensure only the correct definitions are pulled in. 
Once this PR is merged in, I'll work to add it to the `apollo-federation-subgraph-compatibility` repository to denote support, but an updated result shows: 
| Language | Library | Federation 1 Support | Federation 2 Support |
| --- | --- | --- | --- |
| Python | …
=> Feature: Basic Federation 2 Support

ariadne/load_schema.py
I find that there are a number of different schema file extensions in use out there in addition to `.graphql`. This PR adds support for some common ones supported by code editors, specifically `.graphqls` and `.gql`
=> fix: add support for other common schema file extensions

.github/workflows/tests.yml
Fixes #969
#963 effectively unlocked most of Ariadne's dev dependencies, but we still need a way to catch situations when releases for those break the project. We could either lock and manually maintain those in `pyproject.toml`, but I think its preferable for library to leave dependency freeze decision for end users in their projects (until I get burned).
This PR extends tests workflow with scheduled run on mondays and wednesdays on 7 AM UTC time.
=> Auto-run tests suite bi-weekly to catch eventual dependency breaks

ariadne/asgi/handlers/graphql_transport_ws.py
"Unexpected ASGI message 'websocket.close', after sending 'websocket.close'." exception appears in the server logs.
This is caused by the handle_connection_init_timeout handler that is not checking if the WebSocket is already disconnected.
=> fixed websocket.close call on already closed websocket instance

pyproject.toml, tests/test_dataloaders.py
Ariadne now supports custom execution context, but `graphql-sync-dataloaders` is python 3.8 and later only, so we need to skip it for python 3.7
=> Fix python 3.7 build

CHANGELOG.md, ariadne/asgi/handlers/base.py, ariadne/asgi/handlers/http.py, ariadne/extensions.py, ariadne/graphql.py, ariadne/types.py, ariadne/wsgi.py
Changes `middleware` option on ASGI and WSGI apps to be either:
- `None`
- List of middlewares
- Callable returning either `None` or list of middlewares
Also added `middleware_management_class` option for middleware manager customization.
This is departure from current implementation that required `MiddlewareManager` in place of middlewares list, but that's better for two reasons:
- Our docs already tell people to pass Middlewares list
- Extensions discarded whatever MiddlewareManager was used and replaced it with standard one.
Fixes #256
=> Tweak middleware options

CHANGELOG.md, ariadne/asgi/handlers/base.py, ariadne/asgi/handlers/graphql_transport_ws.py, ariadne/asgi/handlers/graphql_ws.py, ariadne/asgi/handlers/http.py, ariadne/types.py, ariadne/wsgi.py, tests/asgi/test_configuration.py, tests/wsgi/test_configuration.py
Currently `context_value` function is called with single argument: instance of HTTP request specific to the framework.
It may be useful for context creation to access cleaned query payload, eg. to pre-warm custom query parser which doesn't support async for performance reasons.
Fixes #843
=> Add data as second argument to context_value callable

ariadne/enums.py, tests/test_enums.py
Cherry-pick fix for enums as default values from Ariadne 0.17.1
=> Port enums fix from 0.17.1 release

CHANGELOG.md, ariadne/__init__.py, ariadne/executable_schema.py, ariadne/schema_names.py, tests/test_schema_names_conversion.py
Supersedes #905
Adds `convert_names_case` to `make_executable_schema`. This option accepts bool or callable:
If `convert_names_case` is set to `True`, `make_executable_schema` will walk the schema:
- For fields without resolver, new resolver will be set that converts field's name to python case using `convert_camel_case_to_snake`. Eg. `userName` will be resolved to `user_name`.
- For input fields `out_name` will be set from its name, meaning that `isClosed` field will be stored on `is_closed` dictionary key passed to resolver 
- For arguments `out_name`  will be set from argument name, meaning that `sendWelcomeEmail: bool` argument's value will be passed to `send_welcome_email` resolver's kwarg.
If `convert_names_case` is a function, `make_executable_schema` will walk the schema:
- For …
=> Add option for names conversion to `make_executable_schema`

ariadne/load_schema.py, tests/test_schema_file_load.py
Otherwise, a call like `load_schema_from_path(dir)`, with `dir = pathlib.Path(...)`, is being reported by mypy as an error.
=> Make load-schema functions accept path-like objects

.pylintrc, ariadne/__init__.py, ariadne/enums.py, ariadne/exceptions.py, ariadne/executable_schema.py, ariadne/extensions.py, ariadne/file_uploads.py, ariadne/format_error.py, ariadne/graphql.py, ariadne/interfaces.py, ariadne/load_schema.py, ariadne/objects.py, ariadne/resolvers.py, ariadne/scalars.py, ariadne/schema_names.py, ariadne/schema_visitor.py, ariadne/subscriptions.py, ariadne/types.py, ariadne/unions.py, ariadne/utils.py, generate_reference.py, pyproject.toml
This PR adds docstrings to public API. It also adds `generate_reference.py` script that generates document with API reference from code. This document can then be moved to ariadne-website repo to update the docs with API reference.
Reasoning for this **big** change is making our API reference docs easier to maintain.
=> Generate reference docs

tests/asgi/test_configuration.py
Our tests ocasionally fail due to race condition in `test_handle_connection_init_timeout_handler_executed_graphql_transport_ws`. I'll open an issue for this later, but in the meantime I would like to make this test don't fail the suite when fail happens.
=> Add xfail to ws connection init timeout test

ariadne/executable_schema.py
Small wording change: `unknown` -> `unsupported`
=> Tweak normalization error message

CHANGELOG.md, ariadne/contrib/federation/schema.py
Reverts mirumee/ariadne#1045 because it broke our tests.
=> Revert "Add convert_names_case to make_federated_schema"

CHANGELOG.md, ariadne/__init__.py, ariadne/executable_schema.py, ariadne/inputs.py, tests/test_inputs.py, tests_mypy/inputs.py
Adds `InputType` which enables setting custom Python representations for GraphQL inputs, eg:
```python
@dataclass
class InputDataclass:
id: str
message: str
year_of_birth: int
input_type = InputType(
"ExampleInput",
lambda data: InputDataclass(**data),
{"yearOfBirth": "year_of_birth"},
)
```
Fixes #333
=> Add `InputType`

CHANGELOG.md, ariadne/contrib/federation/definitions/fed1_0.graphql, ariadne/contrib/federation/definitions/fed2_0.graphql, ariadne/contrib/federation/definitions/fed2_1.graphql, ariadne/contrib/federation/definitions/fed2_2.graphql, ariadne/contrib/federation/definitions/fed2_3.graphql, ariadne/contrib/federation/schema.py, ariadne/contrib/federation/utils.py, tests/federation/test_schema.py, tests/federation/test_schema_v2.py
Apollo release a new version of Federation, version 2.3. Part of this release is the support for the `@interfaceObject` directive, which will allow users to extend/reference Entities from other subgraphs that are interfaces. You can read more about `@interfaceObject` directive here: https://github.com/mirumee/ariadne/issues/1032
This PR is an initial step into adding support for newer spec versions (`v2.1`, `v2.2` and `v2.3`), but the changes are very minimal so we unlock the work we have in progress regarding `Interface Entities`.
* This PR only adds definitions for all the newer spec versions (`v2.1`, `v2.2` and `v2.3`), but it doesn't add functionality for some of the features part of these new spec versions (for example `@composeDirective`), so it will unblock our migration from …
=> feat: add support for @interfaceObject directive

CHANGELOG.md, ariadne/contrib/federation/utils.py, tests/federation/test_utils.py
As written, this regex requires two delimiters before a `directive @custom on FIELD` definition. In some cases (for example, when the preceding line is a comment), this causes `purge_schema_directives` to remove only the `@custom` part, leaving `directive on FIELD` which causes downstream parsing errors.
The solution is to require the second delimiter only if the description is also present.
=> Fix federation support for directives without surrounding whitespace

CHANGELOG.md, ariadne/asgi/graphql.py, ariadne/asgi/handlers/base.py, ariadne/asgi/handlers/graphql_transport_ws.py, ariadne/asgi/handlers/graphql_ws.py, ariadne/asgi/handlers/http.py, ariadne/graphql.py, ariadne/types.py, ariadne/wsgi.py, tests/asgi/test_configuration.py, tests/asgi/test_websockets_graphql_transport_ws.py, tests/asgi/test_websockets_graphql_ws.py, tests/wsgi/test_configuration.py
Please consider this small contribution made in the footsteps of https://github.com/mirumee/ariadne/pull/977. The general idea is that validation can equally benefit from customization to achieve for example memoization as it can get quite expensive for large queries under high QPS. Currently this is not possible without patching ariadne/graphql validate functions. There could have been perhaps a higher level abstraction to memoize both parsing and validation in a single step, but given present semantics this seems more appropriate.
This PR adds query_validator option to the WSGI and ASGI GraphQL applications. This feature opens gate to implementing custom base query validator that (for example) allows to cache validation of query documents.
=> Make query validator configurable

CHANGELOG.md, ariadne/asgi/handlers/graphql_transport_ws.py, tests/asgi/snapshots/snap_test_query_execution.py, tests/asgi/test_websockets_graphql_transport_ws.py
`payload` attribute of `ERROR` message in `graphql-ws` should be list of errors, not an error.
Fixes #1053
=> Fix error message invalid payload

ariadne/validation/query_cost.py, tests/test_query_cost_validation.py
Hey 👋
Fix for query cost validation skipping fragment and inline fragment spreads. Resolves #1078
=> Fix query cost validation

.github/workflows/benchmark.yml
Changes benchmarks so they are only ran on demand. To trigger benchmarks you need to create "benchmark-" tag.
=> Run benchmarks only on demand

.github/workflows/benchmark.yml, .github/workflows/publish.yml, .github/workflows/tests.yml, CHANGELOG.md, pyproject.toml, tests/test_dataloaders.py, tests/wsgi/test_configuration.py
Python 3.7 support ends on 27th of June, in 3 weeks. Flask already abandoned support for it in latest release, I think its safe for us to do it too.
=> Remove Python 3.7 support

ariadne/asgi/__init__.py, ariadne/asgi/handlers/graphql_ws.py, ariadne/exceptions.py, ariadne/types.py, tests/asgi/test_websockets_graphql_transport_ws.py, tests/asgi/test_websockets_graphql_ws.py
Addressing issue #1026 
There was a request for this, and it seems clearer to have the WebSocketConnectionError with the other exceptions rather than with the types.
=> Move WebSocketConnectionError to exceptions (#1026)

CHANGELOG.md, ariadne/asgi/handlers/graphql_transport_ws.py, tests/asgi/__snapshots__/test_websockets_graphql_transport_ws.ambr, tests/asgi/test_websockets_graphql_transport_ws.py
=> Fix GraphQLTransportWSHandler returning invalid error message for `query` and `mutation` errors.

CHANGELOG.md, pyproject.toml
- Deprecated `EnumType.bind_to_default_values` method. It will be removed in a future release.
- Added `repair_schema_default_enum_values` to public API.
- Removed `validate_schema_enum_values` and introduced `validate_schema_default_enum_values` in its place. This is a breaking change.
- Fixed an invalid error message returned by the `GraphQLTransportWSHandler` for `query` and `mutation` operations.
=> Release Ariadne 0.22 Beta 1

tests/asgi/test_configuration.py, tests/asgi/test_websockets_graphql_transport_ws.py
Starlette changed `WebSocketDisconnect` which prevents pytest's `pytest.raises(..., match="")` to work anymore.
=> Fix websockets tests for new Starlette

CHANGELOG.md, ariadne/asgi/graphql.py, ariadne/asgi/handlers/base.py, ariadne/asgi/handlers/http.py, ariadne/graphql.py, ariadne/wsgi.py, tests/asgi/test_configuration.py, tests/wsgi/test_configuration.py
Adds support for executing GraphQL queries sent over GET, as per [spec](https://graphql.org/learn/serving-over-http/#get-request).
Fixes #123
=> Execute queries over GET

CHANGELOG.md, ariadne/graphql.py, tests/asgi/__snapshots__/test_query_execution.ambr, tests/asgi/test_query_execution.py, tests/wsgi/__snapshots__/test_query_execution.ambr, tests/wsgi/test_query_execution.py
=> Prevent subscription execution without websocket

CHANGELOG.md, ariadne/resolvers.py, tests/test_default_resolvers.py
- added support for resolving trivial nested fields
Closes #1181
=> feat: improved alias resolvers (#1181)

tests/asgi/test_configuration.py
I want to merge this change because I consider it as the quickfix for the failing test caused by https://github.com/mirumee/ariadne/issues/1217.
=> Skip websocket init timeout test

pyproject.toml
I want to merge this change because I consider it as the quick fix for the https://github.com/mirumee/ariadne/issues/1216 - it could be unpinned when long-term solution for handling default values will be implemented.
=> Pin graphql-core <3.2.6

.github/workflows/tests.yml, ariadne/contrib/relay/__init__.py, ariadne/contrib/relay/arguments.py, ariadne/contrib/relay/connection.py, ariadne/contrib/relay/objects.py, ariadne/contrib/relay/types.py, ariadne/schema_visitor.py, ariadne/utils.py, pyproject.toml, tests/relay/conftest.py, tests/relay/test_arguments.py, tests/relay/test_connection.py, tests/relay/test_objects.py
Related to https://github.com/mirumee/ariadne/discussions/1213.
> [!IMPORTANT]  
> The schema used for this example comes from https://relay.dev/docs/guides/graphql-server-specification/#schema
Doc strings with examples are yet to come so here's a brief manual on how to use this:
```python
from ariadne.contrib.relay import (
ConnectionArgumentsUnion,
RelayConnection,
RelayObjectType,
RelayQueryType,
)
```
Use the QueryType that enforces the `node` GQL logic while providing some utility:
```python
query = RelayQueryType()
@query.field("node")
async def resolve_node(_, info, bid: str):
ships = [{"__typename": "Ship", **ship} for ship in SHIPS if ship["id"] == bid]
return ships[0]
@query.node.type_resolver
def resolve_node_type(obj, *_):
return obj["__typename"]
```
or if you have the node …
=> Adding contrib for GraphQL Relay

ariadne/contrib/relay/connection.py, ariadne/contrib/relay/objects.py, tests/relay/test_objects.py
The pull request fix missing `totalCount` key in relay connection response.
Additionally handle a scenario when empty list of edges is passed to `RelayConnection`
=> fix(relay): add missing key in return RelayObjectType.resolve_wrapper

ariadne/contrib/federation/interfaces.py, ariadne/contrib/federation/objects.py, ariadne/contrib/federation/schema.py, ariadne/contrib/federation/utils.py, ariadne/contrib/relay/objects.py, ariadne/utils.py, tests/relay/test_objects.py
This pull request uses the `object_type.extensions` argument to store the resolvers used by Relay and Federation.
The `extensions` argument gets copied when `graphql.extend_schema` is used, ensuring the resolvers are kept around when schemas evolve dynamically. The added attributes done via `setattr` are not copied. The federation module worked around this by providing a `extend_federated_schema` function which copied those extra arguments. This function is no longer needed and now throws a deprecation warning.
=> use graphql core extensions field to store contrib resolvers

ariadne/contrib/relay/__init__.py, ariadne/contrib/relay/connection.py, ariadne/contrib/relay/objects.py, ariadne/contrib/relay/types.py, ariadne/contrib/relay/utils.py, pyproject.toml, tests/relay/conftest.py, tests/relay/test_objects.py, tests/relay/test_utils.py
BREAKING CHANGE: the global ID function takes only a str with the GID, the query type uses the `id_field` arg to determine which kwarg to pass to the decoder
One would be able to do:
```python
query = RelayQueryType(
id_field="bid",
)
```
Instead of this:
```python
def decode_global_id(kwargs) -> GlobalIDTuple:
return GlobalIDTuple(*b64decode(kwargs["bid"]).decode().split(":"))
query = RelayQueryType(
global_id_decoder=decode_global_id,
)
```
With the following: https://github.com/mirumee/ariadne/blob/2c8f064c4538bd26e709ed8da665c2236fcbb906/ariadne/contrib/relay/objects.py#L122
This is to make the decoder a bit dummer as to take the responsibility of pulling the GID from the right kwarg (or query param, if you will) from the decoder and leave it with the single responsibility.
=> feat!: add a default global ID encoder, add a id_field on the query type

ariadne/asgi/handlers/graphql_transport_ws.py, tests/asgi/test_configuration.py
In case of `connection_init_wait_timeout` set to 0, ws connection was closed before it was even accepted, so accepting connection was throwing an error. Moving `websocket.accept()` to the top fixes the issue. 
Fixes https://github.com/mirumee/ariadne/issues/1217
=> fix: websocket connection init timeout set to 0

README.md
Since the `ariadne` project has not yet reached a stable API, we are adapting our versioning policy to accommodate ongoing changes.
`ariadne` follows a custom versioning scheme where the minor version increases for breaking changes, while the patch version increments for bug fixes, enhancements, and other non-breaking updates.
Since `ariadne` has not yet reached a stable API, this approach is in place until version 1.0.0. Once the API stabilizes, the project will adopt [Semantic Versioning](https://semver.org/).
=> docs(README.md): Add versioning policy

ariadne/contrib/relay/objects.py, ariadne/utils.py, tests/relay/test_objects.py
This PR ensures that the relay `resolve_wrapper` can handle async functions and objects with an async `__call__` method.
I ran into this issue trying to use the ariadne-auth `authz.require_permission` function alongside the connection class.
`require_permission` converts the decorated resolver into an instance of `PermissionChecker` which defines an `async __call__` and is not picked up by `inspect.iscoroutinefunction`.
The helper function was inspired by [starlette](https://github.com/encode/starlette/blob/cbddcaf59267d5a6e7bf10736cdd5af6048fe274/starlette/_utils.py#L35-L39).
For now, I only added the helper to the connection object, that said, many of the existing usages of `inspect.iscoroutinefunction` will want to move to this helper.
=> check for async callable object and function for relay resolver
