mirumee/ariadne

ariadne/__init__.py
ariadne/resolvers.py
tests/test_queries.py

Add explicit resolver mappings

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Another pass on our meta: updated readme, added code of conduct, stubbed contributing doc.

Add contributing and coc, update readme

---

CONTRIBUTING.md
README.md
docs/conf.py

This PR improves navigation between docs files

Doc tweaks

---

setup.py

This should fix readme display on pypi.

Set long description content type to markdown

---

requirements-dev.in
requirements-dev.txt

Add snapshottest requirement

---

README.md
docs/index.rst

This PR adds features list to readme and docs index.

Add features list to readme and docs index

---

CHANGELOG.md

Fix typo in changelog 0.2.0

---

docs/custom-server.rst

This PR makes the example code runnable with the default Django configuration.

Update Django integration docs

---

tests/test_descriptions.py

This is required for #54.
This is also a prerequisite for #105.
@rafalp Again, let me know if I'm on the right track, or if you'd like me to expand on anything!

Test the GraphQL descriptions feature

---

README.md

Update quickstart guide with latest API changes

---

requirements.txt

This should help straighten out the road to addressing issue #113!
Tests all seem to pass still, but I'm not sure if there's anything else risky about this upgrade.

Upgrade GraphQL core to 1.0.2

---

docs/custom-server.rst

Fixed two typos in the comment of the code example

Fixed typos in code comments

---

README.md

This PR redoes intro in the readme and adds little Mirumee's self promotion bit.

Update readme's self-promotion bits

---

docs/asgi.rst

https://github.com/mirumee/ariadne/blob/ec4a9b9867bc53bda3ed1c1675bf16ff121ddba4/ariadne/asgi.py#L53-L62
These methods must be async, fix example.

doc: fix ASGI example

---

docs/asgi.rst

Update documentation of context_for_request method to match definition

---

.travis.yml
requirements-dev.in
requirements-dev.txt

This PR changes travis config to use requirements-dev.txt instead of explicit pip install test reqs

Update travis config

---

docs/integrations.rst

Integration is fairly straightforward with mounts. Also unifies quotes in the Flask example.

Document integration with Starlette

---

.pylintrc
CHANGELOG.md
ariadne/asgi.py
ariadne/format_error.py
ariadne/graphql.py
ariadne/logger.py
ariadne/utils.py
ariadne/wsgi.py
docs/index.rst
docs/integrations.rst
docs/logging.rst
tests/asgi/snapshots/snap_test_query_execution.py
tests/asgi/test_configuration.py
tests/asgi/test_query_execution.py
tests/asgi/test_websockets.py
tests/conftest.py
tests/wsgi/test_configuration.py

This PR brings some improvements to our error handling:
- wraps async loop consuming payloads for websocket response in try/expect block so we can catch and handle exceptions that occurred in subscription generators.
- adds `logger` option to boilerplate, allowing developers to set custom loggers.
- adds default logger that logs to `ariadne`.

Error handling improvements

---

CHANGELOG.md
setup.py

This PR adds `py.typed` file to `ariadne` package and updates `settings.py` accordingly.

Add py.typed to project

---

ariadne/asgi.py
requirements-dev.in
requirements-dev.txt
requirements.txt
setup.py

Starlette 0.12 is now out of beta, so we can bump our requirements.
Fixes #177

Update Starlette to 0.12

---

CHANGELOG.md
ariadne/__init__.py
ariadne/asgi.py
ariadne/constants.py
ariadne/contrib/django/views.py
ariadne/file_uploads.py
ariadne/graphql.py
ariadne/wsgi.py
requirements.txt
setup.py
tests/asgi/snapshots/snap_test_query_execution.py
tests/asgi/snapshots/snap_test_request_data_reading.py
tests/asgi/test_query_execution.py
tests/asgi/test_request_data_reading.py
tests/conftest.py
tests/django/snapshots/snap_test_query_execution.py
tests/django/test_query_execution.py
tests/test_file_uploads.py
tests/wsgi/factories.py
tests/wsgi/snapshots/snap_test_query_execution.py
tests/wsgi/snapshots/snap_test_request_data_reading.py
tests/wsgi/test_query_execution.py
tests/wsgi/test_request_data_reading.py

This PR adds handling for `multipart/form-data` requests to Ariadne, thus supporting file uploads.
Fixes #186

Add file upload support

---

tests/test_enums.py

This PR improves our enum tests a little:
- Removed `TEST_VALUE` & friends
- Added tests for `StrEnum(str, Enum)` value resolution
Fixes #200

Improve enum tests

---

CHANGELOG.md
ariadne/asgi.py

Fix sub complete

---

CHANGELOG.md
ariadne/asgi.py
ariadne/extensions.py
ariadne/wsgi.py
tests/asgi/test_configuration.py
tests/asgi/test_query_execution.py
tests/wsgi/test_configuration.py

This PR includes #223 but also synces `middleware` option behavior with `extensions`. It also adds tests and changelog.

Sync middleware implementation with extensions

---

README.md

Some folks are asking where's the repo for docs, so I've added a link to those to readme.

Add docs repo url to readme

---

ariadne/schema_visitor.py
tests/test_directives.py

This PR is a follow-up for #222. It adds extra test cases and cleanups code to be more in line with our conventions.

Small schema directive cleanups

---

ariadne/schema_visitor.py

Implementing my first GQL directive, I came across an error... it seemed like a typo when I looked around the code. It worked with this, feel free to discard if it needs more attention.

fixed healing GraphQLUnionType

---

tests/test_directives.py

This PR adds test posted by @0x1EE7 in #249 to our test suite

Add test case for unused directive being defined in schema

---

CHANGELOG.md

This PR adds Ariadne 0.7 release to changelog.

Update changelog to include version 0.7.0

---

CHANGELOG.md
requirements.txt
setup.py
tests/asgi/snapshots/snap_test_query_execution.py
tests/wsgi/snapshots/snap_test_query_execution.py

Update graphql-core-next to graphql-core 3.x

---

ariadne/contrib/federation/utils.py
tests/federation/test_schema.py

This PR allows using async reference resolvers.
Fixes #307

Handle async reference resolvers

---

CHANGELOG.md
README.md
setup.py

New release changelog

---

.editorconfig

While I was making my other PR, I noticed that this project doesn't have an Editor Config, so I added one.

Adds Editor Config to Enforce no Tabs and Consistent Editor Spacing.

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/issue_or_bug_report.md
README.md

Add link to the Spectrum service

---

ariadne/contrib/django/views.py
tests/django/test_configuration.py

I thought Ariadne could support Apollo tracing in a Django GraphQL project: we need to pass `extensions` down to `graphql_sync`, it's as easy as this PR.

Enable extensions with the Django integration

---

ariadne/contrib/django/scalars.py
tests/django/test_scalars.py

Add `Time` scalar along with the existing `Date` and `DateTime`
PR for the docs: https://github.com/mirumee/ariadne-website/pull/66

Add Time scalar

---

ariadne/asgi.py
ariadne/contrib/django/views.py
ariadne/contrib/federation/interfaces.py
ariadne/contrib/federation/objects.py
ariadne/contrib/federation/schema.py
ariadne/contrib/federation/utils.py
ariadne/file_uploads.py
ariadne/graphql.py
ariadne/load_schema.py
ariadne/validation/introspection_disabled.py
ariadne/validation/query_cost.py
ariadne/wsgi.py
tests/asgi/test_websockets.py
tests/federation/test_schema.py
tests/test_kwargs_camel_case_conversion.py

Fix formatting using black

---

CHANGELOG.md
setup.py

Bumps version to 0.13 and fills in changelog.
Fixes #479

Bump version to 0.13, add changelog

---

.github/ISSUE_TEMPLATE/config.yml

Discussion channel changed from spectrum to GH discussions.

Change discussions url

---

requirements-dev.txt

Commits from: #501, #502, #525, #526 + fix dependency for python 3.9

Fixing builds dependabot

---

requirements-dev.txt

Dependabot PR's: #532, #534, #540 + fixing build for python 3.9

Fixing builds dependabot pt2

---

requirements.txt

Regens `requirements.txt`, effectively updating our deps.

Regen requirements.txt instead of updating it

---

ariadne/contrib/django/views.py

Fixed incorrect default playground options structure in Django view

Fix default playground options in Django view

---

CHANGELOG.md
ariadne/contrib/federation/schema.py
ariadne/executable_schema.py
tests/federation/test_schema.py

Fixes #522, initally tested with: https://github.com/kuchichan/ariadne-federation-multiple-keys (Query removed from product service)
Todo:

[Federation]  Query validation

---

CHANGELOG.md
ariadne/resolvers.py
ariadne/utils.py
tests/conftest.py
tests/test_kwargs_camel_case_conversion.py

Fix "isinstance" across default resolvers

---

CHANGELOG.md
ariadne/asgi.py
ariadne/exceptions.py
ariadne/wsgi.py
tests/asgi/test_http_methods.py
tests/wsgi/test_configuration.py
tests/wsgi/test_http_error_handling.py
tests/wsgi/test_query_execution.py
tests/wsgi/test_request_dispatching.py

Adds basic handling for options request. If you need CORS you still should wrap Ariadne in proper HTTP framework for that.
Fixes #664

Handle options requests

---

.github/dependabot.yml
requirements-dev.in
requirements-dev.txt

Removes django from dev reqs and dependabot.

Remove django from dev deps and dependabot

---

ariadne/contrib/federation/utils.py
tests/federation/test_utils.py

Fix federation support for custom directives with descriptions.

---

CHANGELOG.md
requirements.txt
setup.py

Update starlette support to <0.19

---

CHANGELOG.md
ariadne/graphql.py

This PR contains changes from #824 + updated changelog

Use execute_sync instead of execute in graphql_sync

---

ariadne/graphql.py

Use `execute_sync` instead of `execute` in `graphql_sync`

---

CHANGELOG.md
requirements.txt
setup.py

Update graphql-core and starlette deps

---

CHANGELOG.md
setup.py

Fixes performance regression in `make_federated_schema`

Bump version to 0.15.1

---

ariadne/asgi/handlers/graphql_ws.py
ariadne/contrib/federation/interfaces.py
ariadne/contrib/federation/objects.py
ariadne/contrib/federation/schema.py
ariadne/contrib/tracing/opentracing.py
ariadne/executable_schema.py
ariadne/extensions.py
ariadne/graphql.py
ariadne/scalars.py
ariadne/types.py

Make types more accurate

---

ariadne/contrib/federation/schema.py
tests/federation/test_schema.py

adds support for @tag direction in a federation v1 schema

fix 876: add support for @tag federation v1 directive

---

.github/workflows/tests.yml
ariadne/asgi/graphql.py
ariadne/asgi/handlers/base.py
ariadne/asgi/handlers/graphql_transport_ws.py
ariadne/asgi/handlers/graphql_ws.py
ariadne/asgi/handlers/http.py
ariadne/contrib/tracing/apollotracing.py
ariadne/contrib/tracing/opentracing.py
ariadne/exceptions.py
ariadne/explorer/apollo.py
ariadne/explorer/graphiql.py
ariadne/explorer/playground.py
ariadne/explorer/template.py
ariadne/extensions.py
ariadne/resolvers.py
ariadne/schema_visitor.py
ariadne/types.py
ariadne/validation/query_cost.py

This PR fixes mypy errors on master. It also adds `--check-untyped-defs` to mypy so it checks functions that don't specify return type (sic!)

Fix mypy errors on master

---

tests/asgi/test_websockets_graphql_transport_ws.py
tests/conftest.py

fix 965 - added test for mutations over websocket

---

CHANGELOG.md
ariadne/asgi/graphql.py
ariadne/asgi/handlers/base.py
ariadne/asgi/handlers/http.py
ariadne/wsgi.py
tests/wsgi/test_configuration.py

Add execution_context_class option to ASGI and WSGI apps

---

tests/federation/test_schema.py
tests/federation/test_utils.py

Adds tests for #876 and #930
Those were reported as issues with Ariadne but I can't reproduce them or make tests fail.

Add extra tests for edge cases in purge_schema_directives

---

.pylintrc
CHANGELOG.md
ariadne/graphql.py
ariadne/types.py
tests/asgi/test_configuration.py
tests/wsgi/test_configuration.py

Pass operation name and variables to root value callable

---

CHANGELOG.md
ariadne/asgi/graphql.py
ariadne/asgi/handlers/__init__.py
ariadne/asgi/handlers/base.py
ariadne/asgi/handlers/graphql_transport_ws.py
ariadne/asgi/handlers/graphql_ws.py
ariadne/asgi/handlers/http.py
ariadne/graphql.py
ariadne/types.py
ariadne/wsgi.py
generate_reference.py

Add codedocs to `ariadne.types`, `ariadne.wsgi` and `ariadne.asgi`

---

ariadne/enums.py
tests_mypy/enums.py

Update typing for values in EnumType.__init__

---

CHANGELOG.md
ariadne/contrib/federation/schema.py
ariadne/executable_schema.py
tests/test_enums.py
tests_mypy/enums.py

Pass enums directly to make executable schema

---

CHANGELOG.md
ariadne/contrib/federation/schema.py

Add convert_names_case to make_federated_schema

---

CHANGELOG.md
ariadne/contrib/federation/schema.py

Attempt 2, with more imports this time :D

Add convert names case to make federated schema

---

CHANGELOG.md
ariadne/enums.py
tests/test_enums.py

Fix `make_executable_schema` error for default null value for input arg.

---

CHANGELOG.md
pyproject.toml

- Updates changelog
- Bumps version to 0.21

Release Ariadne 0.21

---

ariadne/graphql.py
ariadne/types.py
tests/conftest.py
tests/test_graphql.py

Fixes #1167
Skips changelog because its kind of private-ish API.

Add hack for updating final result with data from root value

---

CHANGELOG.md
ariadne/schema_visitor.py
tests/test_directives.py

Fixes: https://github.com/mirumee/ariadne/issues/420

raise-error-when-directive-declaration-is-missing

---

ariadne/contrib/tracing/copy_args.py
ariadne/contrib/tracing/utils.py
ariadne/wsgi.py
pyproject.toml

Fixes [1208](https://github.com/mirumee/ariadne/issues/1208)

Fix python_multipart deprecation warning

---

.github/workflows/test.yml
README.md
pyproject.toml

This PR adds (restores) a CI action to send coverage report to codecov.io.
It also adds nice PyPI badges to README file.

Restore codecov integration
